### PR TITLE
add polymorphism python

### PR DESCRIPTION
**Pull request by b1gvini**
I have add python polymorphism example.

### CODE REVIEW

**Review by cherryWood55 — COMMENTED** [review]
Thank you for your contribution @b1gvini . Would you please add some comment lines to make the code beginner-friendly?

**Comment by b1gvini** [comment]
Done!

**Comment by b1gvini** [comment]
Will you merge the code?

**Comment by cherryWood55** [comment]
> 
> 
> Will you merge the code?

Merged

**Pull request merged**
